/*
 * Created on 21 fev 2018 ( Time 15:06:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import br.com.ibrowse.web.common.AbstractController;
import br.com.ibrowse.web.common.FormMode;
import br.com.ibrowse.web.common.Message;
import br.com.ibrowse.web.common.MessageType;

//--- Entities
import br.com.ibrowse.bean.Usuarios;

//--- Services 
import br.com.ibrowse.business.service.UsuariosService;


/**
 * Spring MVC controller for 'Usuarios' management.
 */
@Controller
@RequestMapping("/usuarios")
public class UsuariosController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "usuarios";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "usuarios/form";
	private static final String JSP_LIST   = "usuarios/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/usuarios/create";
	private static final String SAVE_ACTION_UPDATE   = "/usuarios/update";

	//--- Main entity service
	@Resource
    private UsuariosService usuariosService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public UsuariosController() {
		super(UsuariosController.class, MAIN_ENTITY_NAME );
		log("UsuariosController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param usuarios
	 */
	private void populateModel(Model model, Usuarios usuarios, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, usuarios);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Usuarios found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Usuarios> list = usuariosService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Usuarios
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Usuarios usuarios = new Usuarios();	
		populateModel( model, usuarios, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Usuarios
	 * @param model Spring MVC model
	 * @param oidUsuarios  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{oidUsuarios}")
	public String formForUpdate(Model model, @PathVariable("oidUsuarios") Long oidUsuarios ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Usuarios usuarios = usuariosService.findById(oidUsuarios);
		populateModel( model, usuarios, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param usuarios  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Usuarios usuarios, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Usuarios usuariosCreated = usuariosService.create(usuarios); 
				model.addAttribute(MAIN_ENTITY_NAME, usuariosCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, usuarios.getOidUsuarios() );
			} else {
				populateModel( model, usuarios, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "usuarios.error.create", e);
			populateModel( model, usuarios, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param usuarios  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Usuarios usuarios, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Usuarios usuariosSaved = usuariosService.update(usuarios);
				model.addAttribute(MAIN_ENTITY_NAME, usuariosSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, usuarios.getOidUsuarios());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, usuarios, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "usuarios.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, usuarios, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param oidUsuarios  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{oidUsuarios}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("oidUsuarios") Long oidUsuarios) {
		log("Action 'delete'" );
		try {
			usuariosService.delete( oidUsuarios );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "usuarios.error.delete", e);
		}
		return redirectToList();
	}

}
