/*
 * Created on 23 mai 2017 ( Time 18:19:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service;

import java.util.List;

import br.com.ibrowse.bean.Bancos;

/**
 * Business Service Interface for entity Bancos.
 */
public interface BancosService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param oidBancos
	 * @return entity
	 */
	Bancos findById( Long oidBancos  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Bancos> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Bancos save(Bancos entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bancos update(Bancos entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Bancos create(Bancos entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param oidBancos
	 */
	void delete( Long oidBancos );


}
