/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service;

import java.util.List;

import br.com.ibrowse.bean.CentrosCustos;

/**
 * Business Service Interface for entity CentrosCustos.
 */
public interface CentrosCustosService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param oidCentrosCustos
	 * @return entity
	 */
	CentrosCustos findById( Long oidCentrosCustos  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<CentrosCustos> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CentrosCustos save(CentrosCustos entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CentrosCustos update(CentrosCustos entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CentrosCustos create(CentrosCustos entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param oidCentrosCustos
	 */
	void delete( Long oidCentrosCustos );


}
