/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service;

import java.util.List;

import br.com.ibrowse.bean.ContasReceber;

/**
 * Business Service Interface for entity ContasReceber.
 */
public interface ContasReceberService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param oidContasReceber
	 * @return entity
	 */
	ContasReceber findById( Long oidContasReceber  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ContasReceber> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ContasReceber save(ContasReceber entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasReceber update(ContasReceber entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasReceber create(ContasReceber entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param oidContasReceber
	 */
	void delete( Long oidContasReceber );


}
