/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service;

import java.util.List;

import br.com.ibrowse.bean.ContasPagarRateio;

/**
 * Business Service Interface for entity ContasPagarRateio.
 */
public interface ContasPagarRateioService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param oidContasPagarRateio
	 * @return entity
	 */
	ContasPagarRateio findById( Long oidContasPagarRateio  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ContasPagarRateio> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ContasPagarRateio save(ContasPagarRateio entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasPagarRateio update(ContasPagarRateio entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasPagarRateio create(ContasPagarRateio entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param oidContasPagarRateio
	 */
	void delete( Long oidContasPagarRateio );


}
