/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service;

import java.util.List;

import br.com.ibrowse.bean.ContasPagar;

/**
 * Business Service Interface for entity ContasPagar.
 */
public interface ContasPagarService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param oidContasPagar
	 * @return entity
	 */
	ContasPagar findById( Long oidContasPagar  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<ContasPagar> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ContasPagar save(ContasPagar entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasPagar update(ContasPagar entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ContasPagar create(ContasPagar entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param oidContasPagar
	 */
	void delete( Long oidContasPagar );


}
