/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import br.com.ibrowse.bean.ContasPagarRateio;
import br.com.ibrowse.bean.jpa.ContasPagarRateioEntity;
import br.com.ibrowse.business.service.ContasPagarRateioService;
import br.com.ibrowse.business.service.mapping.ContasPagarRateioServiceMapper;
import br.com.ibrowse.data.repository.jpa.ContasPagarRateioJpaRepository;

/**
 * Implementation of ContasPagarRateioService
 */
@Component
@Transactional
public class ContasPagarRateioServiceImpl implements ContasPagarRateioService {

	@Resource
	private ContasPagarRateioJpaRepository contasPagarRateioJpaRepository;

	@Resource
	private ContasPagarRateioServiceMapper contasPagarRateioServiceMapper;
	
	@Override
	public ContasPagarRateio findById(Long oidContasPagarRateio) {
		ContasPagarRateioEntity contasPagarRateioEntity = contasPagarRateioJpaRepository.findOne(oidContasPagarRateio);
		return contasPagarRateioServiceMapper.mapContasPagarRateioEntityToContasPagarRateio(contasPagarRateioEntity);
	}

	@Override
	public List<ContasPagarRateio> findAll() {
		Iterable<ContasPagarRateioEntity> entities = contasPagarRateioJpaRepository.findAll();
		List<ContasPagarRateio> beans = new ArrayList<ContasPagarRateio>();
		for(ContasPagarRateioEntity contasPagarRateioEntity : entities) {
			beans.add(contasPagarRateioServiceMapper.mapContasPagarRateioEntityToContasPagarRateio(contasPagarRateioEntity));
		}
		return beans;
	}

	@Override
	public ContasPagarRateio save(ContasPagarRateio contasPagarRateio) {
		return update(contasPagarRateio) ;
	}

	@Override
	public ContasPagarRateio create(ContasPagarRateio contasPagarRateio) {
		ContasPagarRateioEntity contasPagarRateioEntity = contasPagarRateioJpaRepository.findOne(contasPagarRateio.getOidContasPagarRateio());
		if( contasPagarRateioEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		contasPagarRateioEntity = new ContasPagarRateioEntity();
		contasPagarRateioServiceMapper.mapContasPagarRateioToContasPagarRateioEntity(contasPagarRateio, contasPagarRateioEntity);
		ContasPagarRateioEntity contasPagarRateioEntitySaved = contasPagarRateioJpaRepository.save(contasPagarRateioEntity);
		return contasPagarRateioServiceMapper.mapContasPagarRateioEntityToContasPagarRateio(contasPagarRateioEntitySaved);
	}

	@Override
	public ContasPagarRateio update(ContasPagarRateio contasPagarRateio) {
		ContasPagarRateioEntity contasPagarRateioEntity = contasPagarRateioJpaRepository.findOne(contasPagarRateio.getOidContasPagarRateio());
		contasPagarRateioServiceMapper.mapContasPagarRateioToContasPagarRateioEntity(contasPagarRateio, contasPagarRateioEntity);
		ContasPagarRateioEntity contasPagarRateioEntitySaved = contasPagarRateioJpaRepository.save(contasPagarRateioEntity);
		return contasPagarRateioServiceMapper.mapContasPagarRateioEntityToContasPagarRateio(contasPagarRateioEntitySaved);
	}

	@Override
	public void delete(Long oidContasPagarRateio) {
		contasPagarRateioJpaRepository.delete(oidContasPagarRateio);
	}

	public ContasPagarRateioJpaRepository getContasPagarRateioJpaRepository() {
		return contasPagarRateioJpaRepository;
	}

	public void setContasPagarRateioJpaRepository(ContasPagarRateioJpaRepository contasPagarRateioJpaRepository) {
		this.contasPagarRateioJpaRepository = contasPagarRateioJpaRepository;
	}

	public ContasPagarRateioServiceMapper getContasPagarRateioServiceMapper() {
		return contasPagarRateioServiceMapper;
	}

	public void setContasPagarRateioServiceMapper(ContasPagarRateioServiceMapper contasPagarRateioServiceMapper) {
		this.contasPagarRateioServiceMapper = contasPagarRateioServiceMapper;
	}

}
