/*
 * Created on 23 mai 2017 ( Time 18:19:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.web.listitem;

import br.com.ibrowse.bean.Bancos;
import br.com.ibrowse.web.common.ListItem;

public class BancosListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BancosListItem(Bancos bancos) {
		super();

		this.value = ""
			 + bancos.getOidBancos()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = bancos.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
