/*
 * Created on 23 mai 2017 ( Time 18:19:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.web.listitem;

import br.com.ibrowse.bean.CentrosCustos;
import br.com.ibrowse.web.common.ListItem;

public class CentrosCustosListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public CentrosCustosListItem(CentrosCustos centrosCustos) {
		super();

		this.value = ""
			 + centrosCustos.getOidCentrosCustos()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = centrosCustos.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
