/*
 * Created on 21 fev 2018 ( Time 15:06:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.web.listitem;

import br.com.ibrowse.bean.Usuarios;
import br.com.ibrowse.web.common.ListItem;

public class UsuariosListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public UsuariosListItem(Usuarios usuarios) {
		super();

		this.value = ""
			 + usuarios.getOidUsuarios()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = usuarios.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
