/*
 * Created on 23 mai 2017 ( Time 18:19:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Bancos implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long oidBancos;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Long cdBanco;

    @NotNull
    @Size( min = 1, max = 100 )
    private String nmBanco;

    @NotNull
    @Size( min = 1, max = 20 )
    private String nmAbreviado;

    @NotNull
    @Size( min = 1, max = 30 )
    private String dsUsuAlter = "IBROWSE";

    @NotNull
    private Date dtUltAlter = new Date();

    @NotNull
    private Long vsVersao = 0L;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidBancos( Long oidBancos ) {
        this.oidBancos = oidBancos ;
    }

    public Long getOidBancos() {
        return this.oidBancos;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCdBanco( Long cdBanco ) {
        this.cdBanco = cdBanco;
    }
    public Long getCdBanco() {
        return this.cdBanco;
    }

    public void setNmBanco( String nmBanco ) {
        this.nmBanco = nmBanco;
    }
    public String getNmBanco() {
        return this.nmBanco;
    }

    public void setNmAbreviado( String nmAbreviado ) {
        this.nmAbreviado = nmAbreviado;
    }
    public String getNmAbreviado() {
        return this.nmAbreviado;
    }

    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(cdBanco);
        sb.append(" - ");
        sb.append(nmBanco);
        return sb.toString(); 
    } 


}
