/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class ContasPagarRateio implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long oidContasPagarRateio;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String oidContasPagar;

    @NotNull
    private Long oidCentrosCustos;

    @NotNull
    private Long vrRateio;

    @NotNull
    @Size( min = 1, max = 30 )
    private String dsUsuAlter = "IBROWSE";

    @NotNull
    private Date dtUltAlter = new Date();

    @NotNull
    private Long vsVersao = 0L;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidContasPagarRateio( Long oidContasPagarRateio ) {
        this.oidContasPagarRateio = oidContasPagarRateio ;
    }

    public Long getOidContasPagarRateio() {
        return this.oidContasPagarRateio;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setOidContasPagar( String oidContasPagar ) {
        this.oidContasPagar = oidContasPagar;
    }
    public String getOidContasPagar() {
        return this.oidContasPagar;
    }

    public void setOidCentrosCustos( Long oidCentrosCustos ) {
        this.oidCentrosCustos = oidCentrosCustos;
    }
    public Long getOidCentrosCustos() {
        return this.oidCentrosCustos;
    }

    public void setVrRateio( Long vrRateio ) {
        this.vrRateio = vrRateio;
    }
    public Long getVrRateio() {
        return this.vrRateio;
    }

    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(oidContasPagarRateio);
        sb.append("|");
        sb.append(oidContasPagar);
        sb.append("|");
        sb.append(oidCentrosCustos);
        sb.append("|");
        sb.append(vrRateio);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 


}
