/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Pessoas implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long oidPessoas;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String nmPessoa;

    @Size( max = 14 )
    private String nrCpfCnpj;

    @Size( max = 50 )
    private String nmCidade;

    @Size( max = 2 )
    private String nmUf;

    @Size( max = 11 )
    private String nrTelefone;

    @Size( max = 100 )
    private String nmContato;

    @Size( max = 100 )
    private String nrEmail;


    private Long vrPercDeducaoIrpj = 0L;


    private Long vrPercDeducaoPis = 0L;


    private Long vrPercDeducaoCofins = 0L;


    private Long vrPercDeducaoCsll = 0L;


    private Long vrPercDeducaoInss = 0L;


    private Long vrPercDeducaoIssqn = 0L;

    @NotNull
    @Size( min = 1, max = 30 )
    private String dsUsuAlter = "IBROWSE";

    @NotNull
    private Date dtUltAlter = new Date();

    @NotNull
    private Long vsVersao = 0L;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidPessoas( Long oidPessoas ) {
        this.oidPessoas = oidPessoas ;
    }

    public Long getOidPessoas() {
        return this.oidPessoas;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNmPessoa( String nmPessoa ) {
        this.nmPessoa = nmPessoa;
    }
    public String getNmPessoa() {
        return this.nmPessoa;
    }

    public void setNrCpfCnpj( String nrCpfCnpj ) {
        this.nrCpfCnpj = nrCpfCnpj;
    }
    public String getNrCpfCnpj() {
        return this.nrCpfCnpj;
    }

    public void setNmCidade( String nmCidade ) {
        this.nmCidade = nmCidade;
    }
    public String getNmCidade() {
        return this.nmCidade;
    }

    public void setNmUf( String nmUf ) {
        this.nmUf = nmUf;
    }
    public String getNmUf() {
        return this.nmUf;
    }

    public void setNrTelefone( String nrTelefone ) {
        this.nrTelefone = nrTelefone;
    }
    public String getNrTelefone() {
        return this.nrTelefone;
    }

    public void setNmContato( String nmContato ) {
        this.nmContato = nmContato;
    }
    public String getNmContato() {
        return this.nmContato;
    }

    public void setNrEmail( String nrEmail ) {
        this.nrEmail = nrEmail;
    }
    public String getNrEmail() {
        return this.nrEmail;
    }

    public void setVrPercDeducaoIrpj( Long vrPercDeducaoIrpj ) {
        this.vrPercDeducaoIrpj = vrPercDeducaoIrpj;
    }
    public Long getVrPercDeducaoIrpj() {
        return this.vrPercDeducaoIrpj;
    }

    public void setVrPercDeducaoPis( Long vrPercDeducaoPis ) {
        this.vrPercDeducaoPis = vrPercDeducaoPis;
    }
    public Long getVrPercDeducaoPis() {
        return this.vrPercDeducaoPis;
    }

    public void setVrPercDeducaoCofins( Long vrPercDeducaoCofins ) {
        this.vrPercDeducaoCofins = vrPercDeducaoCofins;
    }
    public Long getVrPercDeducaoCofins() {
        return this.vrPercDeducaoCofins;
    }

    public void setVrPercDeducaoCsll( Long vrPercDeducaoCsll ) {
        this.vrPercDeducaoCsll = vrPercDeducaoCsll;
    }
    public Long getVrPercDeducaoCsll() {
        return this.vrPercDeducaoCsll;
    }

    public void setVrPercDeducaoInss( Long vrPercDeducaoInss ) {
        this.vrPercDeducaoInss = vrPercDeducaoInss;
    }
    public Long getVrPercDeducaoInss() {
        return this.vrPercDeducaoInss;
    }

    public void setVrPercDeducaoIssqn( Long vrPercDeducaoIssqn ) {
        this.vrPercDeducaoIssqn = vrPercDeducaoIssqn;
    }
    public Long getVrPercDeducaoIssqn() {
        return this.vrPercDeducaoIssqn;
    }

    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(oidPessoas);
        sb.append(" - ");
        sb.append(nmPessoa);
        return sb.toString(); 
    } 


}
