/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class TiposTitulos implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    private Long oidTiposTitulos;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 100 )
    private String dsTiposTitulos;

    @NotNull
    @Size( min = 1, max = 30 )
    private String dsUsuAlter = "IBROWSE";

    @NotNull
    private Date dtUltAlter = new Date();

    @NotNull
    private Long vsVersao = 0L;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidTiposTitulos( Long oidTiposTitulos ) {
        this.oidTiposTitulos = oidTiposTitulos ;
    }

    public Long getOidTiposTitulos() {
        return this.oidTiposTitulos;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDsTiposTitulos( String dsTiposTitulos ) {
        this.dsTiposTitulos = dsTiposTitulos;
    }
    public String getDsTiposTitulos() {
        return this.dsTiposTitulos;
    }

    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(oidTiposTitulos);
        sb.append(" - ");
        sb.append(dsTiposTitulos);
        return sb.toString(); 
    } 


}
