/*
 * Created on 21 fev 2018 ( Time 15:06:03 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.math.BigDecimal;
import java.util.Date;

public class Usuarios implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Long oidUsuarios;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 20 )
    private String nmUsuario;

    @NotNull
    @Size( min = 1, max = 10 )
    private String senha;

    @Size( max = 40 )
    private String nomeCompleto;

    @Size( max = 40 )
    private String email;

    @NotNull
    @Size( min = 1, max = 30 )
    private String dsUsuAlter;

    @NotNull
    private Date dtUltAlter;

    @NotNull
    private Long vsVersao;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidUsuarios( Long oidUsuarios ) {
        this.oidUsuarios = oidUsuarios ;
    }

    public Long getOidUsuarios() {
        return this.oidUsuarios;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNmUsuario( String nmUsuario ) {
        this.nmUsuario = nmUsuario;
    }
    public String getNmUsuario() {
        return this.nmUsuario;
    }

    public void setSenha( String senha ) {
        this.senha = senha;
    }
    public String getSenha() {
        return this.senha;
    }

    public void setNomeCompleto( String nomeCompleto ) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }

    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(oidUsuarios);
        sb.append("|");
        sb.append(nmUsuario);
        sb.append("|");
        sb.append(senha);
        sb.append("|");
        sb.append(nomeCompleto);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 


}
