/*
 * Created on 23 mai 2017 ( Time 18:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package br.com.ibrowse.bean.jpa;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "BANCOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="BANCOS", schema="DB_FINANCEIRO" )
@SequenceGenerator(name="SE_BANCOS", sequenceName="SE_BANCOS")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BancosEntity.countAll", query="SELECT COUNT(x) FROM BancosEntity x" )
} )
public class BancosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="SE_BANCOS")
    @Column(name="OID_BANCOS", nullable=false)
    private Long oidBancos    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="CD_BANCO", nullable=false)
    private Long cdBanco      ;

    @Column(name="NM_BANCO", nullable=false, length=100)
    private String     nmBanco      ;

    @Column(name="NM_ABREVIADO", nullable=false, length=20)
    private String     nmAbreviado  ;

    @Column(name="DS_USU_ALTER", nullable=false, length=30)
    private String     dsUsuAlter   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULT_ALTER", nullable=false)
    private Date       dtUltAlter   ;

    @Column(name="VS_VERSAO", nullable=false)
    private Long vsVersao     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BancosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidBancos( Long oidBancos ) {
        this.oidBancos = oidBancos ;
    }
    public Long getOidBancos() {
        return this.oidBancos;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : CD_BANCO ( NUMBER ) 
    public void setCdBanco( Long cdBanco ) {
        this.cdBanco = cdBanco;
    }
    public Long getCdBanco() {
        return this.cdBanco;
    }

    //--- DATABASE MAPPING : NM_BANCO ( VARCHAR2 ) 
    public void setNmBanco( String nmBanco ) {
        this.nmBanco = nmBanco;
    }
    public String getNmBanco() {
        return this.nmBanco;
    }

    //--- DATABASE MAPPING : NM_ABREVIADO ( VARCHAR2 ) 
    public void setNmAbreviado( String nmAbreviado ) {
        this.nmAbreviado = nmAbreviado;
    }
    public String getNmAbreviado() {
        return this.nmAbreviado;
    }

    //--- DATABASE MAPPING : DS_USU_ALTER ( VARCHAR2 ) 
    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    //--- DATABASE MAPPING : DT_ULT_ALTER ( DATE ) 
    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    //--- DATABASE MAPPING : VS_VERSAO ( NUMBER ) 
    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(oidBancos);
        sb.append("]:"); 
        sb.append(cdBanco);
        sb.append("|");
        sb.append(nmBanco);
        sb.append("|");
        sb.append(nmAbreviado);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 

}
