/*
 * Created on 23 mai 2017 ( Time 18:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package br.com.ibrowse.bean.jpa;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "CENTROS_CUSTOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CENTROS_CUSTOS", schema="DB_FINANCEIRO" )
@SequenceGenerator(name="SE_CENTROS_CUSTOS", sequenceName="SE_CENTROS_CUSTOS")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="CentrosCustosEntity.countAll", query="SELECT COUNT(x) FROM CentrosCustosEntity x" )
} )
public class CentrosCustosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="SE_CENTROS_CUSTOS")
    @Column(name="OID_CENTROS_CUSTOS", nullable=false)
    private Long oidCentrosCustos ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DS_CENTROS_CUSTOS", nullable=false, length=100)
    private String     dsCentrosCustos ;

    @Column(name="NM_GERENTE", nullable=false, length=100)
    private String     nmGerente    ;

    @Column(name="DS_USU_ALTER", nullable=false, length=30)
    private String     dsUsuAlter   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULT_ALTER", nullable=false)
    private Date       dtUltAlter   ;

    @Column(name="VS_VERSAO", nullable=false)
    private Long vsVersao     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public CentrosCustosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidCentrosCustos( Long oidCentrosCustos ) {
        this.oidCentrosCustos = oidCentrosCustos ;
    }
    public Long getOidCentrosCustos() {
        return this.oidCentrosCustos;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DS_CENTROS_CUSTOS ( VARCHAR2 ) 
    public void setDsCentrosCustos( String dsCentrosCustos ) {
        this.dsCentrosCustos = dsCentrosCustos;
    }
    public String getDsCentrosCustos() {
        return this.dsCentrosCustos;
    }

    //--- DATABASE MAPPING : NM_GERENTE ( VARCHAR2 ) 
    public void setNmGerente( String nmGerente ) {
        this.nmGerente = nmGerente;
    }
    public String getNmGerente() {
        return this.nmGerente;
    }

    //--- DATABASE MAPPING : DS_USU_ALTER ( VARCHAR2 ) 
    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    //--- DATABASE MAPPING : DT_ULT_ALTER ( DATE ) 
    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    //--- DATABASE MAPPING : VS_VERSAO ( NUMBER ) 
    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(oidCentrosCustos);
        sb.append("]:"); 
        sb.append(dsCentrosCustos);
        sb.append("|");
        sb.append(nmGerente);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 

}
