/*
 * Created on 23 mai 2017 ( Time 18:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package br.com.ibrowse.bean.jpa;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "CONTAS_RECEBER"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CONTAS_RECEBER", schema="DB_FINANCEIRO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ContasReceberEntity.countAll", query="SELECT COUNT(x) FROM ContasReceberEntity x" )
} )
public class ContasReceberEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="OID_CONTAS_RECEBER", nullable=false)
    private Long oidContasReceber ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NR_DOCUMENTO_FISCAL", nullable=false, length=100)
    private String     nrDocumentoFiscal ;

    @Column(name="OID_PESSOAS", nullable=false)
    private Long oidPessoas   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_PREVISAO", nullable=false)
    private Date       dtPrevisao   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_VENCIMENTO", nullable=false)
    private Date       dtVencimento ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_RECEBIMENTO", nullable=false)
    private Date       dtRecebimento ;

    @Column(name="VR_BRUTO", nullable=false)
    private Long vrBruto      ;

    @Column(name="VR_JUROS")
    private Long vrJuros      ;

    @Column(name="VR_DESCONTO")
    private Long vrDesconto   ;

    @Column(name="OID_CENTROS_CUSTOS")
    private Long oidCentrosCustos ;

    @Column(name="OID_BANCOS")
    private Long oidBancos    ;

    @Column(name="DS_FORMA_RECEBIMENTO", length=20)
    private String     dsFormaRecebimento ;

    @Column(name="DS_OBSERVACAO", length=500)
    private String     dsObservacao ;

    @Column(name="VR_BASE_INSS", nullable=false)
    private Long vrBaseInss   ;

    @Column(name="VR_DEDUCAO_INSS", nullable=false)
    private Long vrDeducaoInss ;

    @Column(name="VR_BASE_ISSQN", nullable=false)
    private Long vrBaseIssqn  ;

    @Column(name="VR_DEDUCAO_ISSQN", nullable=false)
    private Long vrDeducaoIssqn ;

    @Column(name="VR_BASE_CSLL", nullable=false)
    private Long vrBaseCsll   ;

    @Column(name="VR_DEDUCAO_CSLL", nullable=false)
    private Long vrDeducaoCsll ;

    @Column(name="VR_BASE_PIS", nullable=false)
    private Long vrBasePis    ;

    @Column(name="VR_DEDUCAO_PIS", nullable=false)
    private Long vrDeducaoPis ;

    @Column(name="VR_BASE_COFINS", nullable=false)
    private Long vrBaseCofins ;

    @Column(name="VR_DEDUCAO_COFINS", nullable=false)
    private Long vrDeducaoCofins ;

    @Column(name="VR_BASE_IRPJ", nullable=false)
    private Long vrBaseIrpj   ;

    @Column(name="VR_DEDUCAO_IRPJ", nullable=false)
    private Long vrDeducaoIrpj ;

    @Column(name="VR_OUTRAS_DEDUCOES", nullable=false)
    private Long vrOutrasDeducoes ;

    @Column(name="DS_USU_ALTER", nullable=false, length=30)
    private String     dsUsuAlter   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULT_ALTER", nullable=false)
    private Date       dtUltAlter   ;

    @Column(name="VS_VERSAO", nullable=false)
    private Long vsVersao     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ContasReceberEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidContasReceber( Long oidContasReceber ) {
        this.oidContasReceber = oidContasReceber ;
    }
    public Long getOidContasReceber() {
        return this.oidContasReceber;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NR_DOCUMENTO_FISCAL ( VARCHAR2 ) 
    public void setNrDocumentoFiscal( String nrDocumentoFiscal ) {
        this.nrDocumentoFiscal = nrDocumentoFiscal;
    }
    public String getNrDocumentoFiscal() {
        return this.nrDocumentoFiscal;
    }

    //--- DATABASE MAPPING : OID_PESSOAS ( NUMBER ) 
    public void setOidPessoas( Long oidPessoas ) {
        this.oidPessoas = oidPessoas;
    }
    public Long getOidPessoas() {
        return this.oidPessoas;
    }

    //--- DATABASE MAPPING : DT_PREVISAO ( DATE ) 
    public void setDtPrevisao( Date dtPrevisao ) {
        this.dtPrevisao = dtPrevisao;
    }
    public Date getDtPrevisao() {
        return this.dtPrevisao;
    }

    //--- DATABASE MAPPING : DT_VENCIMENTO ( DATE ) 
    public void setDtVencimento( Date dtVencimento ) {
        this.dtVencimento = dtVencimento;
    }
    public Date getDtVencimento() {
        return this.dtVencimento;
    }

    //--- DATABASE MAPPING : DT_RECEBIMENTO ( DATE ) 
    public void setDtRecebimento( Date dtRecebimento ) {
        this.dtRecebimento = dtRecebimento;
    }
    public Date getDtRecebimento() {
        return this.dtRecebimento;
    }

    //--- DATABASE MAPPING : VR_BRUTO ( NUMBER ) 
    public void setVrBruto( Long vrBruto ) {
        this.vrBruto = vrBruto;
    }
    public Long getVrBruto() {
        return this.vrBruto;
    }

    //--- DATABASE MAPPING : VR_JUROS ( NUMBER ) 
    public void setVrJuros( Long vrJuros ) {
        this.vrJuros = vrJuros;
    }
    public Long getVrJuros() {
        return this.vrJuros;
    }

    //--- DATABASE MAPPING : VR_DESCONTO ( NUMBER ) 
    public void setVrDesconto( Long vrDesconto ) {
        this.vrDesconto = vrDesconto;
    }
    public Long getVrDesconto() {
        return this.vrDesconto;
    }

    //--- DATABASE MAPPING : OID_CENTROS_CUSTOS ( NUMBER ) 
    public void setOidCentrosCustos( Long oidCentrosCustos ) {
        this.oidCentrosCustos = oidCentrosCustos;
    }
    public Long getOidCentrosCustos() {
        return this.oidCentrosCustos;
    }

    //--- DATABASE MAPPING : OID_BANCOS ( NUMBER ) 
    public void setOidBancos( Long oidBancos ) {
        this.oidBancos = oidBancos;
    }
    public Long getOidBancos() {
        return this.oidBancos;
    }

    //--- DATABASE MAPPING : DS_FORMA_RECEBIMENTO ( VARCHAR2 ) 
    public void setDsFormaRecebimento( String dsFormaRecebimento ) {
        this.dsFormaRecebimento = dsFormaRecebimento;
    }
    public String getDsFormaRecebimento() {
        return this.dsFormaRecebimento;
    }

    //--- DATABASE MAPPING : DS_OBSERVACAO ( VARCHAR2 ) 
    public void setDsObservacao( String dsObservacao ) {
        this.dsObservacao = dsObservacao;
    }
    public String getDsObservacao() {
        return this.dsObservacao;
    }

    //--- DATABASE MAPPING : VR_BASE_INSS ( NUMBER ) 
    public void setVrBaseInss( Long vrBaseInss ) {
        this.vrBaseInss = vrBaseInss;
    }
    public Long getVrBaseInss() {
        return this.vrBaseInss;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_INSS ( NUMBER ) 
    public void setVrDeducaoInss( Long vrDeducaoInss ) {
        this.vrDeducaoInss = vrDeducaoInss;
    }
    public Long getVrDeducaoInss() {
        return this.vrDeducaoInss;
    }

    //--- DATABASE MAPPING : VR_BASE_ISSQN ( NUMBER ) 
    public void setVrBaseIssqn( Long vrBaseIssqn ) {
        this.vrBaseIssqn = vrBaseIssqn;
    }
    public Long getVrBaseIssqn() {
        return this.vrBaseIssqn;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_ISSQN ( NUMBER ) 
    public void setVrDeducaoIssqn( Long vrDeducaoIssqn ) {
        this.vrDeducaoIssqn = vrDeducaoIssqn;
    }
    public Long getVrDeducaoIssqn() {
        return this.vrDeducaoIssqn;
    }

    //--- DATABASE MAPPING : VR_BASE_CSLL ( NUMBER ) 
    public void setVrBaseCsll( Long vrBaseCsll ) {
        this.vrBaseCsll = vrBaseCsll;
    }
    public Long getVrBaseCsll() {
        return this.vrBaseCsll;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_CSLL ( NUMBER ) 
    public void setVrDeducaoCsll( Long vrDeducaoCsll ) {
        this.vrDeducaoCsll = vrDeducaoCsll;
    }
    public Long getVrDeducaoCsll() {
        return this.vrDeducaoCsll;
    }

    //--- DATABASE MAPPING : VR_BASE_PIS ( NUMBER ) 
    public void setVrBasePis( Long vrBasePis ) {
        this.vrBasePis = vrBasePis;
    }
    public Long getVrBasePis() {
        return this.vrBasePis;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_PIS ( NUMBER ) 
    public void setVrDeducaoPis( Long vrDeducaoPis ) {
        this.vrDeducaoPis = vrDeducaoPis;
    }
    public Long getVrDeducaoPis() {
        return this.vrDeducaoPis;
    }

    //--- DATABASE MAPPING : VR_BASE_COFINS ( NUMBER ) 
    public void setVrBaseCofins( Long vrBaseCofins ) {
        this.vrBaseCofins = vrBaseCofins;
    }
    public Long getVrBaseCofins() {
        return this.vrBaseCofins;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_COFINS ( NUMBER ) 
    public void setVrDeducaoCofins( Long vrDeducaoCofins ) {
        this.vrDeducaoCofins = vrDeducaoCofins;
    }
    public Long getVrDeducaoCofins() {
        return this.vrDeducaoCofins;
    }

    //--- DATABASE MAPPING : VR_BASE_IRPJ ( NUMBER ) 
    public void setVrBaseIrpj( Long vrBaseIrpj ) {
        this.vrBaseIrpj = vrBaseIrpj;
    }
    public Long getVrBaseIrpj() {
        return this.vrBaseIrpj;
    }

    //--- DATABASE MAPPING : VR_DEDUCAO_IRPJ ( NUMBER ) 
    public void setVrDeducaoIrpj( Long vrDeducaoIrpj ) {
        this.vrDeducaoIrpj = vrDeducaoIrpj;
    }
    public Long getVrDeducaoIrpj() {
        return this.vrDeducaoIrpj;
    }

    //--- DATABASE MAPPING : VR_OUTRAS_DEDUCOES ( NUMBER ) 
    public void setVrOutrasDeducoes( Long vrOutrasDeducoes ) {
        this.vrOutrasDeducoes = vrOutrasDeducoes;
    }
    public Long getVrOutrasDeducoes() {
        return this.vrOutrasDeducoes;
    }

    //--- DATABASE MAPPING : DS_USU_ALTER ( VARCHAR2 ) 
    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    //--- DATABASE MAPPING : DT_ULT_ALTER ( DATE ) 
    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    //--- DATABASE MAPPING : VS_VERSAO ( NUMBER ) 
    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(oidContasReceber);
        sb.append("]:"); 
        sb.append(nrDocumentoFiscal);
        sb.append("|");
        sb.append(oidPessoas);
        sb.append("|");
        sb.append(dtPrevisao);
        sb.append("|");
        sb.append(dtVencimento);
        sb.append("|");
        sb.append(dtRecebimento);
        sb.append("|");
        sb.append(vrBruto);
        sb.append("|");
        sb.append(vrJuros);
        sb.append("|");
        sb.append(vrDesconto);
        sb.append("|");
        sb.append(oidCentrosCustos);
        sb.append("|");
        sb.append(oidBancos);
        sb.append("|");
        sb.append(dsFormaRecebimento);
        sb.append("|");
        sb.append(dsObservacao);
        sb.append("|");
        sb.append(vrBaseInss);
        sb.append("|");
        sb.append(vrDeducaoInss);
        sb.append("|");
        sb.append(vrBaseIssqn);
        sb.append("|");
        sb.append(vrDeducaoIssqn);
        sb.append("|");
        sb.append(vrBaseCsll);
        sb.append("|");
        sb.append(vrDeducaoCsll);
        sb.append("|");
        sb.append(vrBasePis);
        sb.append("|");
        sb.append(vrDeducaoPis);
        sb.append("|");
        sb.append(vrBaseCofins);
        sb.append("|");
        sb.append(vrDeducaoCofins);
        sb.append("|");
        sb.append(vrBaseIrpj);
        sb.append("|");
        sb.append(vrDeducaoIrpj);
        sb.append("|");
        sb.append(vrOutrasDeducoes);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 

}
