/*
 * Created on 23 mai 2017 ( Time 18:19:32 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package br.com.ibrowse.bean.jpa;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "PESSOAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="PESSOAS", schema="DB_FINANCEIRO" )
@SequenceGenerator(name="SE_PESSOAS", sequenceName="SE_PESSOAS")
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PessoasEntity.countAll", query="SELECT COUNT(x) FROM PessoasEntity x" )
} )
public class PessoasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id @GeneratedValue(strategy=GenerationType.AUTO, generator="SE_PESSOAS")
    @Column(name="OID_PESSOAS", nullable=false)
    private Long oidPessoas   ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NM_PESSOA", nullable=false, length=100)
    private String     nmPessoa     ;

    @Column(name="NR_CPF_CNPJ", length=14)
    private String     nrCpfCnpj    ;

    @Column(name="NM_CIDADE", length=50)
    private String     nmCidade     ;

    @Column(name="NM_UF", length=2)
    private String     nmUf         ;

    @Column(name="NR_TELEFONE", length=11)
    private String     nrTelefone   ;

    @Column(name="NM_CONTATO", length=100)
    private String     nmContato    ;
    
    @Column(name="NR_EMAIL", length=100)
    private String     nrEmail      ;

    @Column(name="VR_PERC_DEDUCAO_IRPJ")
    private Long vrPercDeducaoIrpj = 0L;

    @Column(name="VR_PERC_DEDUCAO_PIS")
    private Long vrPercDeducaoPis = 0L;

    @Column(name="VR_PERC_DEDUCAO_COFINS")
    private Long vrPercDeducaoCofins = 0L;

    @Column(name="VR_PERC_DEDUCAO_CSLL")
    private Long vrPercDeducaoCsll = 0L;

    @Column(name="VR_PERC_DEDUCAO_INSS")
    private Long vrPercDeducaoInss = 0L;

    @Column(name="VR_PERC_DEDUCAO_ISSQN")
    private Long vrPercDeducaoIssqn = 0L;

    @Column(name="DS_USU_ALTER", nullable=false, length=30)
    private String     dsUsuAlter   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULT_ALTER", nullable=false)
    private Date       dtUltAlter   ;

    @Column(name="VS_VERSAO", nullable=false)
    private Long vsVersao     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PessoasEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidPessoas( Long oidPessoas ) {
        this.oidPessoas = oidPessoas ;
    }
    public Long getOidPessoas() {
        return this.oidPessoas;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NM_PESSOA ( VARCHAR2 ) 
    public void setNmPessoa( String nmPessoa ) {
        this.nmPessoa = nmPessoa;
    }
    public String getNmPessoa() {
        return this.nmPessoa;
    }

    //--- DATABASE MAPPING : NR_CPF_CNPJ ( VARCHAR2 ) 
    public void setNrCpfCnpj( String nrCpfCnpj ) {
        this.nrCpfCnpj = nrCpfCnpj;
    }
    public String getNrCpfCnpj() {
        return this.nrCpfCnpj;
    }

    //--- DATABASE MAPPING : NM_CIDADE ( VARCHAR2 ) 
    public void setNmCidade( String nmCidade ) {
        this.nmCidade = nmCidade;
    }
    public String getNmCidade() {
        return this.nmCidade;
    }

    //--- DATABASE MAPPING : NM_UF ( VARCHAR2 ) 
    public void setNmUf( String nmUf ) {
        this.nmUf = nmUf;
    }
    public String getNmUf() {
        return this.nmUf;
    }

    //--- DATABASE MAPPING : NR_TELEFONE ( VARCHAR2 ) 
    public void setNrTelefone( String nrTelefone ) {
        this.nrTelefone = nrTelefone;
    }
    public String getNrTelefone() {
        return this.nrTelefone;
    }

    //--- DATABASE MAPPING : NM_CONTATO ( VARCHAR2 ) 
    public void setNmContato( String nmContato ) {
        this.nmContato = nmContato;
    }
    public String getNmContato() {
        return this.nmContato;
    }

    //--- DATABASE MAPPING : NR_EMAIL ( VARCHAR2 ) 
    public void setNrEmail( String nrEmail ) {
        this.nrEmail = nrEmail;
    }
    public String getNrEmail() {
        return this.nrEmail;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_IRPJ ( NUMBER ) 
    public void setVrPercDeducaoIrpj( Long vrPercDeducaoIrpj ) {
        this.vrPercDeducaoIrpj = vrPercDeducaoIrpj;
    }
    public Long getVrPercDeducaoIrpj() {
        return this.vrPercDeducaoIrpj;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_PIS ( NUMBER ) 
    public void setVrPercDeducaoPis( Long vrPercDeducaoPis ) {
        this.vrPercDeducaoPis = vrPercDeducaoPis;
    }
    public Long getVrPercDeducaoPis() {
        return this.vrPercDeducaoPis;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_COFINS ( NUMBER ) 
    public void setVrPercDeducaoCofins( Long vrPercDeducaoCofins ) {
        this.vrPercDeducaoCofins = vrPercDeducaoCofins;
    }
    public Long getVrPercDeducaoCofins() {
        return this.vrPercDeducaoCofins;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_CSLL ( NUMBER ) 
    public void setVrPercDeducaoCsll( Long vrPercDeducaoCsll ) {
        this.vrPercDeducaoCsll = vrPercDeducaoCsll;
    }
    public Long getVrPercDeducaoCsll() {
        return this.vrPercDeducaoCsll;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_INSS ( NUMBER ) 
    public void setVrPercDeducaoInss( Long vrPercDeducaoInss ) {
        this.vrPercDeducaoInss = vrPercDeducaoInss;
    }
    public Long getVrPercDeducaoInss() {
        return this.vrPercDeducaoInss;
    }

    //--- DATABASE MAPPING : VR_PERC_DEDUCAO_ISSQN ( NUMBER ) 
    public void setVrPercDeducaoIssqn( Long vrPercDeducaoIssqn ) {
        this.vrPercDeducaoIssqn = vrPercDeducaoIssqn;
    }
    public Long getVrPercDeducaoIssqn() {
        return this.vrPercDeducaoIssqn;
    }

    //--- DATABASE MAPPING : DS_USU_ALTER ( VARCHAR2 ) 
    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    //--- DATABASE MAPPING : DT_ULT_ALTER ( DATE ) 
    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    //--- DATABASE MAPPING : VS_VERSAO ( NUMBER ) 
    public void setVsVersao( Long vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public Long getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(oidPessoas);
        sb.append("]:"); 
        sb.append(nmPessoa);
        sb.append("|");
        sb.append(nrCpfCnpj);
        sb.append("|");
        sb.append(nmCidade);
        sb.append("|");
        sb.append(nmUf);
        sb.append("|");
        sb.append(nrTelefone);
        sb.append("|");
        sb.append(nmContato);
        sb.append("|");
        sb.append(nrEmail);
        sb.append("|");
        sb.append(vrPercDeducaoIrpj);
        sb.append("|");
        sb.append(vrPercDeducaoPis);
        sb.append("|");
        sb.append(vrPercDeducaoCofins);
        sb.append("|");
        sb.append(vrPercDeducaoCsll);
        sb.append("|");
        sb.append(vrPercDeducaoInss);
        sb.append("|");
        sb.append(vrPercDeducaoIssqn);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 

}
