/*
 * Created on 21 fev 2018 ( Time 15:05:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package br.com.ibrowse.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "USUARIOS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="USUARIOS", schema="DB_FINANCEIRO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="UsuariosEntity.countAll", query="SELECT COUNT(x) FROM UsuariosEntity x" )
} )
public class UsuariosEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="OID_USUARIOS", nullable=false)
    private BigDecimal oidUsuarios  ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NM_USUARIO", nullable=false, length=20)
    private String     nmUsuario    ;

    @Column(name="SENHA", nullable=false, length=10)
    private String     senha        ;

    @Column(name="NOME_COMPLETO", length=40)
    private String     nomeCompleto ;

    @Column(name="EMAIL", length=40)
    private String     email        ;

    @Column(name="DS_USU_ALTER", nullable=false, length=30)
    private String     dsUsuAlter   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_ULT_ALTER", nullable=false)
    private Date       dtUltAlter   ;

    @Column(name="VS_VERSAO", nullable=false)
    private BigDecimal vsVersao     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public UsuariosEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOidUsuarios( BigDecimal oidUsuarios ) {
        this.oidUsuarios = oidUsuarios ;
    }
    public BigDecimal getOidUsuarios() {
        return this.oidUsuarios;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NM_USUARIO ( VARCHAR2 ) 
    public void setNmUsuario( String nmUsuario ) {
        this.nmUsuario = nmUsuario;
    }
    public String getNmUsuario() {
        return this.nmUsuario;
    }

    //--- DATABASE MAPPING : SENHA ( VARCHAR2 ) 
    public void setSenha( String senha ) {
        this.senha = senha;
    }
    public String getSenha() {
        return this.senha;
    }

    //--- DATABASE MAPPING : NOME_COMPLETO ( VARCHAR2 ) 
    public void setNomeCompleto( String nomeCompleto ) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }

    //--- DATABASE MAPPING : EMAIL ( VARCHAR2 ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : DS_USU_ALTER ( VARCHAR2 ) 
    public void setDsUsuAlter( String dsUsuAlter ) {
        this.dsUsuAlter = dsUsuAlter;
    }
    public String getDsUsuAlter() {
        return this.dsUsuAlter;
    }

    //--- DATABASE MAPPING : DT_ULT_ALTER ( DATE ) 
    public void setDtUltAlter( Date dtUltAlter ) {
        this.dtUltAlter = dtUltAlter;
    }
    public Date getDtUltAlter() {
        return this.dtUltAlter;
    }

    //--- DATABASE MAPPING : VS_VERSAO ( NUMBER ) 
    public void setVsVersao( BigDecimal vsVersao ) {
        this.vsVersao = vsVersao;
    }
    public BigDecimal getVsVersao() {
        return this.vsVersao;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(oidUsuarios);
        sb.append("]:"); 
        sb.append(nmUsuario);
        sb.append("|");
        sb.append(senha);
        sb.append("|");
        sb.append(nomeCompleto);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(dsUsuAlter);
        sb.append("|");
        sb.append(dtUltAlter);
        sb.append("|");
        sb.append(vsVersao);
        return sb.toString(); 
    } 

}
