/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.Bancos;
import br.com.ibrowse.bean.jpa.BancosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class BancosServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public BancosServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'BancosEntity' to 'Bancos'
	 * @param bancosEntity
	 */
	public Bancos mapBancosEntityToBancos(BancosEntity bancosEntity) {
		if(bancosEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Bancos bancos = map(bancosEntity, Bancos.class);

		return bancos;
	}
	
	/**
	 * Mapping from 'Bancos' to 'BancosEntity'
	 * @param bancos
	 * @param bancosEntity
	 */
	public void mapBancosToBancosEntity(Bancos bancos, BancosEntity bancosEntity) {
		if(bancos == null) {
			return;
		}

		//--- Generic mapping 
		map(bancos, bancosEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}