/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.CentrosCustos;
import br.com.ibrowse.bean.jpa.CentrosCustosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CentrosCustosServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CentrosCustosServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CentrosCustosEntity' to 'CentrosCustos'
	 * @param centrosCustosEntity
	 */
	public CentrosCustos mapCentrosCustosEntityToCentrosCustos(CentrosCustosEntity centrosCustosEntity) {
		if(centrosCustosEntity == null) {
			return null;
		}

		//--- Generic mapping 
		CentrosCustos centrosCustos = map(centrosCustosEntity, CentrosCustos.class);

		return centrosCustos;
	}
	
	/**
	 * Mapping from 'CentrosCustos' to 'CentrosCustosEntity'
	 * @param centrosCustos
	 * @param centrosCustosEntity
	 */
	public void mapCentrosCustosToCentrosCustosEntity(CentrosCustos centrosCustos, CentrosCustosEntity centrosCustosEntity) {
		if(centrosCustos == null) {
			return;
		}

		//--- Generic mapping 
		map(centrosCustos, centrosCustosEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}