/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.ContasPagarRateio;
import br.com.ibrowse.bean.jpa.ContasPagarRateioEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ContasPagarRateioServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ContasPagarRateioServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ContasPagarRateioEntity' to 'ContasPagarRateio'
	 * @param contasPagarRateioEntity
	 */
	public ContasPagarRateio mapContasPagarRateioEntityToContasPagarRateio(ContasPagarRateioEntity contasPagarRateioEntity) {
		if(contasPagarRateioEntity == null) {
			return null;
		}

		//--- Generic mapping 
		ContasPagarRateio contasPagarRateio = map(contasPagarRateioEntity, ContasPagarRateio.class);

		return contasPagarRateio;
	}
	
	/**
	 * Mapping from 'ContasPagarRateio' to 'ContasPagarRateioEntity'
	 * @param contasPagarRateio
	 * @param contasPagarRateioEntity
	 */
	public void mapContasPagarRateioToContasPagarRateioEntity(ContasPagarRateio contasPagarRateio, ContasPagarRateioEntity contasPagarRateioEntity) {
		if(contasPagarRateio == null) {
			return;
		}

		//--- Generic mapping 
		map(contasPagarRateio, contasPagarRateioEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}