/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.ContasPagar;
import br.com.ibrowse.bean.jpa.BancosEntity;
import br.com.ibrowse.bean.jpa.CentrosCustosEntity;
import br.com.ibrowse.bean.jpa.ContasPagarEntity;
import br.com.ibrowse.bean.jpa.PessoasEntity;
import br.com.ibrowse.bean.jpa.TiposTitulosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ContasPagarServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ContasPagarServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ContasPagarEntity' to 'ContasPagar'
	 * @param contasPagarEntity
	 */
	public ContasPagar mapContasPagarEntityToContasPagar(ContasPagarEntity contasPagarEntity) {
		if(contasPagarEntity == null) {
			return null;
		}

		//--- Generic mapping 
		
		ContasPagar contasPagar = map(contasPagarEntity, ContasPagar.class);
		contasPagar.setPessoa(contasPagarEntity.getPessoas());
		contasPagar.setOidPessoas(contasPagarEntity.getPessoas().getOidPessoas());
		//contasPagar.setTiposTitulo(contasPagarEntity.getTiposTitulos());
		//contasPagar.setOidTiposTitulos(contasPagarEntity.getTiposTitulos().getOidTiposTitulos());
		contasPagar.setCentrosCusto(contasPagarEntity.getCentrosCustos());
		contasPagar.setOidCentrosCustos(contasPagarEntity.getCentrosCustos().getOidCentrosCustos());
		contasPagar.setBanco(contasPagarEntity.getBancos());
		contasPagar.setOidBancos(contasPagarEntity.getBancos().getOidBancos());

		return contasPagar;
	}
	
	/**
	 * Mapping from 'ContasPagar' to 'ContasPagarEntity'
	 * @param contasPagar
	 * @param contasPagarEntity
	 */
	public void mapContasPagarToContasPagarEntity(ContasPagar contasPagar, ContasPagarEntity contasPagarEntity) {
		if(contasPagar == null) {
			return;
		}

		//--- Generic mapping 
		contasPagarEntity.setPessoas(new PessoasEntity());
		//contasPagarEntity.setTiposTitulos(new TiposTitulosEntity());
		contasPagarEntity.setBancos(new BancosEntity());
		contasPagarEntity.setCentrosCustos(new CentrosCustosEntity());
		contasPagarEntity.getPessoas().setOidPessoas(contasPagar.getOidPessoas());
		//contasPagarEntity.getTiposTitulos().setOidTiposTitulos(contasPagar.getOidTiposTitulos());
		contasPagarEntity.getCentrosCustos().setOidCentrosCustos(contasPagar.getOidCentrosCustos());
		contasPagarEntity.getBancos().setOidBancos(contasPagar.getOidBancos());
		map(contasPagar, contasPagarEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}