/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.TiposTitulos;
import br.com.ibrowse.bean.jpa.TiposTitulosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TiposTitulosServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TiposTitulosServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TiposTitulosEntity' to 'TiposTitulos'
	 * @param tiposTitulosEntity
	 */
	public TiposTitulos mapTiposTitulosEntityToTiposTitulos(TiposTitulosEntity tiposTitulosEntity) {
		if(tiposTitulosEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TiposTitulos tiposTitulos = map(tiposTitulosEntity, TiposTitulos.class);

		return tiposTitulos;
	}
	
	/**
	 * Mapping from 'TiposTitulos' to 'TiposTitulosEntity'
	 * @param tiposTitulos
	 * @param tiposTitulosEntity
	 */
	public void mapTiposTitulosToTiposTitulosEntity(TiposTitulos tiposTitulos, TiposTitulosEntity tiposTitulosEntity) {
		if(tiposTitulos == null) {
			return;
		}

		//--- Generic mapping 
		map(tiposTitulos, tiposTitulosEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}