/*
 * Created on 21 fev 2018 ( Time 15:05:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import br.com.ibrowse.bean.Usuarios;
import br.com.ibrowse.bean.jpa.UsuariosEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UsuariosServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UsuariosServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UsuariosEntity' to 'Usuarios'
	 * @param usuariosEntity
	 */
	public Usuarios mapUsuariosEntityToUsuarios(UsuariosEntity usuariosEntity) {
		if(usuariosEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Usuarios usuarios = map(usuariosEntity, Usuarios.class);

		return usuarios;
	}
	
	/**
	 * Mapping from 'Usuarios' to 'UsuariosEntity'
	 * @param usuarios
	 * @param usuariosEntity
	 */
	public void mapUsuariosToUsuariosEntity(Usuarios usuarios, UsuariosEntity usuariosEntity) {
		if(usuarios == null) {
			return;
		}

		//--- Generic mapping 
		map(usuarios, usuariosEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}