/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import br.com.ibrowse.bean.CentrosCustos;
import br.com.ibrowse.business.service.CentrosCustosService;
import br.com.ibrowse.web.listitem.CentrosCustosListItem;

/**
 * Spring MVC controller for 'CentrosCustos' management.
 */
@Controller
public class CentrosCustosRestController {

	@Resource
	private CentrosCustosService centrosCustosService;
	
	@RequestMapping( value="/items/centrosCustos",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CentrosCustosListItem> findAllAsListItems() {
		List<CentrosCustos> list = centrosCustosService.findAll();
		List<CentrosCustosListItem> items = new LinkedList<CentrosCustosListItem>();
		for ( CentrosCustos centrosCustos : list ) {
			items.add(new CentrosCustosListItem( centrosCustos ) );
		}
		return items;
	}
	
	@RequestMapping( value="/centrosCustos",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<CentrosCustos> findAll() {
		return centrosCustosService.findAll();
	}

	@RequestMapping( value="/centrosCustos/{oidCentrosCustos}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CentrosCustos findOne(@PathVariable("oidCentrosCustos") Long oidCentrosCustos) {
		return centrosCustosService.findById(oidCentrosCustos);
	}
	
	@RequestMapping( value="/centrosCustos",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CentrosCustos create(@RequestBody CentrosCustos centrosCustos) {
		return centrosCustosService.create(centrosCustos);
	}

	@RequestMapping( value="/centrosCustos/{oidCentrosCustos}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public CentrosCustos update(@PathVariable("oidCentrosCustos") Long oidCentrosCustos, @RequestBody CentrosCustos centrosCustos) {
		return centrosCustosService.update(centrosCustos);
	}

	@RequestMapping( value="/centrosCustos/{oidCentrosCustos}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("oidCentrosCustos") Long oidCentrosCustos) {
		centrosCustosService.delete(oidCentrosCustos);
	}
	
}
