/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import br.com.ibrowse.bean.ContasPagarRateio;
import br.com.ibrowse.business.service.ContasPagarRateioService;
import br.com.ibrowse.web.listitem.ContasPagarRateioListItem;

/**
 * Spring MVC controller for 'ContasPagarRateio' management.
 */
@Controller
public class ContasPagarRateioRestController {

	@Resource
	private ContasPagarRateioService contasPagarRateioService;
	
	@RequestMapping( value="/items/contasPagarRateio",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContasPagarRateioListItem> findAllAsListItems() {
		List<ContasPagarRateio> list = contasPagarRateioService.findAll();
		List<ContasPagarRateioListItem> items = new LinkedList<ContasPagarRateioListItem>();
		for ( ContasPagarRateio contasPagarRateio : list ) {
			items.add(new ContasPagarRateioListItem( contasPagarRateio ) );
		}
		return items;
	}
	
	@RequestMapping( value="/contasPagarRateio",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContasPagarRateio> findAll() {
		return contasPagarRateioService.findAll();
	}

	@RequestMapping( value="/contasPagarRateio/{oidContasPagarRateio}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagarRateio findOne(@PathVariable("oidContasPagarRateio") Long oidContasPagarRateio) {
		return contasPagarRateioService.findById(oidContasPagarRateio);
	}
	
	@RequestMapping( value="/contasPagarRateio",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagarRateio create(@RequestBody ContasPagarRateio contasPagarRateio) {
		return contasPagarRateioService.create(contasPagarRateio);
	}

	@RequestMapping( value="/contasPagarRateio/{oidContasPagarRateio}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagarRateio update(@PathVariable("oidContasPagarRateio") Long oidContasPagarRateio, @RequestBody ContasPagarRateio contasPagarRateio) {
		return contasPagarRateioService.update(contasPagarRateio);
	}

	@RequestMapping( value="/contasPagarRateio/{oidContasPagarRateio}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("oidContasPagarRateio") Long oidContasPagarRateio) {
		contasPagarRateioService.delete(oidContasPagarRateio);
	}
	
}
