/*
 * Created on 23 mai 2017 ( Time 18:19:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import br.com.ibrowse.bean.ContasPagar;
import br.com.ibrowse.business.service.ContasPagarService;
import br.com.ibrowse.web.listitem.ContasPagarListItem;

/**
 * Spring MVC controller for 'ContasPagar' management.
 */
@Controller
public class ContasPagarRestController {

	@Resource
	private ContasPagarService contasPagarService;
	
	@RequestMapping( value="/items/contasPagar",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContasPagarListItem> findAllAsListItems() {
		List<ContasPagar> list = contasPagarService.findAll();
		List<ContasPagarListItem> items = new LinkedList<ContasPagarListItem>();
		for ( ContasPagar contasPagar : list ) {
			items.add(new ContasPagarListItem( contasPagar ) );
		}
		return items;
	}
	
	@RequestMapping( value="/contasPagar",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ContasPagar> findAll() {
		return contasPagarService.findAll();
	}

	@RequestMapping( value="/contasPagar/{oidContasPagar}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagar findOne(@PathVariable("oidContasPagar") Long oidContasPagar) {
		return contasPagarService.findById(oidContasPagar);
	}
	
	@RequestMapping( value="/contasPagar",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagar create(@RequestBody ContasPagar contasPagar) {
		return contasPagarService.create(contasPagar);
	}

	@RequestMapping( value="/contasPagar/{oidContasPagar}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public ContasPagar update(@PathVariable("oidContasPagar") Long oidContasPagar, @RequestBody ContasPagar contasPagar) {
		return contasPagarService.update(contasPagar);
	}

	@RequestMapping( value="/contasPagar/{oidContasPagar}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("oidContasPagar") Long oidContasPagar) {
		contasPagarService.delete(oidContasPagar);
	}
	
}
