/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;

import br.com.ibrowse.bean.Bancos;
import br.com.ibrowse.bean.jpa.BancosEntity;
import br.com.ibrowse.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class BancosServiceMapperTest {

	private BancosServiceMapper bancosServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		bancosServiceMapper = new BancosServiceMapper();
		bancosServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'BancosEntity' to 'Bancos'
	 * @param bancosEntity
	 */
	@Test
	public void testMapBancosEntityToBancos() {
		// Given
		BancosEntity bancosEntity = new BancosEntity();
		bancosEntity.setCdBanco(mockValues.nextLong());
		bancosEntity.setNmBanco(mockValues.nextString(100));
		bancosEntity.setNmAbreviado(mockValues.nextString(20));
		bancosEntity.setDsUsuAlter(mockValues.nextString(30));
		bancosEntity.setDtUltAlter(mockValues.nextDate());
		bancosEntity.setVsVersao(mockValues.nextLong());
		
		// When
		Bancos bancos = bancosServiceMapper.mapBancosEntityToBancos(bancosEntity);
		
		// Then
		assertEquals(bancosEntity.getCdBanco(), bancos.getCdBanco());
		assertEquals(bancosEntity.getNmBanco(), bancos.getNmBanco());
		assertEquals(bancosEntity.getNmAbreviado(), bancos.getNmAbreviado());
		assertEquals(bancosEntity.getDsUsuAlter(), bancos.getDsUsuAlter());
		assertEquals(bancosEntity.getDtUltAlter(), bancos.getDtUltAlter());
		assertEquals(bancosEntity.getVsVersao(), bancos.getVsVersao());
	}
	
	/**
	 * Test : Mapping from 'Bancos' to 'BancosEntity'
	 */
	@Test
	public void testMapBancosToBancosEntity() {
		// Given
		Bancos bancos = new Bancos();
		bancos.setCdBanco(mockValues.nextLong());
		bancos.setNmBanco(mockValues.nextString(100));
		bancos.setNmAbreviado(mockValues.nextString(20));
		bancos.setDsUsuAlter(mockValues.nextString(30));
		bancos.setDtUltAlter(mockValues.nextDate());
		bancos.setVsVersao(mockValues.nextLong());

		BancosEntity bancosEntity = new BancosEntity();
		
		// When
		bancosServiceMapper.mapBancosToBancosEntity(bancos, bancosEntity);
		
		// Then
		assertEquals(bancos.getCdBanco(), bancosEntity.getCdBanco());
		assertEquals(bancos.getNmBanco(), bancosEntity.getNmBanco());
		assertEquals(bancos.getNmAbreviado(), bancosEntity.getNmAbreviado());
		assertEquals(bancos.getDsUsuAlter(), bancosEntity.getDsUsuAlter());
		assertEquals(bancos.getDtUltAlter(), bancosEntity.getDtUltAlter());
		assertEquals(bancos.getVsVersao(), bancosEntity.getVsVersao());
	}

}