/*
 * Created on 23 mai 2017 ( Time 18:19:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package br.com.ibrowse.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;

import br.com.ibrowse.bean.TiposTitulos;
import br.com.ibrowse.bean.jpa.TiposTitulosEntity;
import br.com.ibrowse.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class TiposTitulosServiceMapperTest {

	private TiposTitulosServiceMapper tiposTitulosServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		tiposTitulosServiceMapper = new TiposTitulosServiceMapper();
		tiposTitulosServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'TiposTitulosEntity' to 'TiposTitulos'
	 * @param tiposTitulosEntity
	 */
	@Test
	public void testMapTiposTitulosEntityToTiposTitulos() {
		// Given
		TiposTitulosEntity tiposTitulosEntity = new TiposTitulosEntity();
		tiposTitulosEntity.setDsTiposTitulos(mockValues.nextString(100));
		tiposTitulosEntity.setDsUsuAlter(mockValues.nextString(30));
		tiposTitulosEntity.setDtUltAlter(mockValues.nextDate());
		tiposTitulosEntity.setVsVersao(mockValues.nextLong());
		
		// When
		TiposTitulos tiposTitulos = tiposTitulosServiceMapper.mapTiposTitulosEntityToTiposTitulos(tiposTitulosEntity);
		
		// Then
		assertEquals(tiposTitulosEntity.getDsTiposTitulos(), tiposTitulos.getDsTiposTitulos());
		assertEquals(tiposTitulosEntity.getDsUsuAlter(), tiposTitulos.getDsUsuAlter());
		assertEquals(tiposTitulosEntity.getDtUltAlter(), tiposTitulos.getDtUltAlter());
		assertEquals(tiposTitulosEntity.getVsVersao(), tiposTitulos.getVsVersao());
	}
	
	/**
	 * Test : Mapping from 'TiposTitulos' to 'TiposTitulosEntity'
	 */
	@Test
	public void testMapTiposTitulosToTiposTitulosEntity() {
		// Given
		TiposTitulos tiposTitulos = new TiposTitulos();
		tiposTitulos.setDsTiposTitulos(mockValues.nextString(100));
		tiposTitulos.setDsUsuAlter(mockValues.nextString(30));
		tiposTitulos.setDtUltAlter(mockValues.nextDate());
		tiposTitulos.setVsVersao(mockValues.nextLong());

		TiposTitulosEntity tiposTitulosEntity = new TiposTitulosEntity();
		
		// When
		tiposTitulosServiceMapper.mapTiposTitulosToTiposTitulosEntity(tiposTitulos, tiposTitulosEntity);
		
		// Then
		assertEquals(tiposTitulos.getDsTiposTitulos(), tiposTitulosEntity.getDsTiposTitulos());
		assertEquals(tiposTitulos.getDsUsuAlter(), tiposTitulosEntity.getDsUsuAlter());
		assertEquals(tiposTitulos.getDtUltAlter(), tiposTitulosEntity.getDtUltAlter());
		assertEquals(tiposTitulos.getVsVersao(), tiposTitulosEntity.getVsVersao());
	}

}